name: Permintaan Fitur Baru
description: Mengusulkan fitur baru
title: "Permintaan fitur: "
labels: ['Fitur']

body:
  - type: textarea
    id: kekurangan
    attributes:
      label: Apa kekurangan yg ingin diatasi?
      placeholder: Beri keterangan singkat dan jelas mengapa fitur ini diperlukan.
    validations:
      required: true

  - type: textarea
    id: solusi
    attributes:
      label: Jelaskan solusi yg diinginkan
      placeholder: |
        Beri keterangan singkat dan jelas mengenai fitur yg diinginkan.
        Beri acuan peraturan yg mendasari fitur ini, kalau ada.
        Lampirkan contoh laporan dan tangkapan layar yang diinginkan.
    validations:
      required: true

  - type: textarea
    id: alternatif
    attributes:
      label: Apakah ada alternatif lain
      placeholder: Beri keterangan singkat dan jelas solusi lain yg telah anda pertimbangkan untuk kebutuhan ini.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Untuk versi OpenSID mana
      placeholder: Fitur ini diusulkan untuk versi Rilis Umum (mis. v21.03) atau Rilis Premium (mis v21.03-premium) yg mana?
    validations:
      required: true

  - type: textarea
    id: tambahan
    attributes:
      label: Informasi tambahan
      placeholder: Beri informasi lainnya yg dapat membantu menjelaskan permintaan ini.
    validations:
      required: false
